### ISSUE TITLE
Unable to serve

### ISSUE THREAD

**Issue by Cthalin** [fabriziosalmi/UglyFeed#17]
Gathering data, processing and converting works fine, but serving the xml does not work for me. I have tried on two docker instances, where executing the serve.py script just results in an endless 'running' without any log errors. I have also tried via cloning the repo and executing the scripts manually via terminal. Here the script starts successfully and giving me the message `'2024-06-09 18:39:32,936 - INFO - Serving uglyfeed.xml at: http://192.168.178.151:8000/uglyfeed.xml'` but when I open up the link I get the message 
```
'192.168.178.151 - - [09/Jun/2024 18:39:36] code 400, message Bad request
192.168.178.151 - - [09/Jun/2024 18:39:36] "GET /uglyfeed.xml HTTP/1.1" 400 -'
```
I have also run a XML checker on the uglyfeed.xml just to be sure it worked fine until that step without any issues.
**To Reproduce**
1. run the scripts until the serving step
2. open the provided link
3. see error 400 in browser and in terminal

**Expected behavior**
A XML response to be seen

**Screenshots**
![image](https://github.com/fabriziosalmi/UglyFeed/assets/12426628/18123380-2206-4e9a-b7c9-b432e0761a46)
![image](https://github.com/fabriziosalmi/UglyFeed/assets/12426628/bea06df7-2de3-4c8d-92f9-333635338b70)

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Browser Chrome
 - Version 125.0.6422.142

I have not found any additional logs.

**Comment by fabriziosalmi** [comment]
can u please try to pull the latest docker image and provide feedback here ? could be really useful since lot of small fixes has been included today :) ty 🍺

**Comment by Cthalin** [comment]
jfyi I will test it and report back, I just don't have the time currently :)

**Comment by fabriziosalmi** [comment]
Helo☕️

I just added the **Deploy** page where you can push the generated XML to GitHub or GitLab and retrieve it using any RSS reader.
That way the HTTP server is not needed anymore.

Deployments scheduler will be added very soon btw ⏰

Another (atm) undocumented way is to access the XML on local machine since it's saved to the `uglyfeeds/uglyfeed.xml` path of the local clones repository 🍻

**Comment by Cthalin** [comment]
Seems like you are faster than me :) I still have to check it out, now with the newest changes. Yes, I know where to find the xml and as a surrogation I just used a nginx container to serve it directly from there for my reader
